---
# We just wrap `build` so this is really it
name: "jellyfin"
version: "10.5.3"
packages:
  - debian-package-x64
  - debian-package-armhf
  - debian-package-arm64
  - ubuntu-package-x64
  - ubuntu-package-armhf
  - ubuntu-package-arm64
  - fedora-package-x64
  - centos-package-x64
  - linux-x64
  - macos
  - portable
  - win-x64
  - win-x86
