#!/usr/bin/env bash

# bump_version - increase the shared version and generate changelogs

set -o errexit
set -o pipefail
set -o xtrace

usage() {
    echo -e "bump_version - increase the shared version"
    echo -e ""
    echo -e "Usage:"
    echo -e " $ bump_version <new_version>"
}

if [[ -z $1 ]]; then
    usage
    exit 1
fi

shared_version_file="./SharedVersion.cs"
# csproj files for nuget packages
jellyfin_subprojects=(
  MediaBrowser.Common/MediaBrowser.Common.csproj
  Jellyfin.Data/Jellyfin.Data.csproj
  MediaBrowser.Controller/MediaBrowser.Controller.csproj
  MediaBrowser.Model/MediaBrowser.Model.csproj
  Emby.Naming/Emby.Naming.csproj
  src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
  src/Jellyfin.MediaEncoding.Keyframes/Jellyfin.MediaEncoding.Keyframes.csproj
  src/Jellyfin.Database/Jellyfin.Database.Implementations/Jellyfin.Database.Implementations.csproj
)
issue_template_file="./.github/ISSUE_TEMPLATE/issue report.yml"
haos_config_file="./haos-jellyfin/config.yaml"
haos_changelog_file="./haos-jellyfin/CHANGELOG.md"

new_version="$1"
new_version_sed="$( cut -f1 -d'-' <<<"${new_version}" )"

# Set the assembly version in SharedVersion.cs
if [[ -f ${shared_version_file} ]]; then
    old_version="$(
        grep -E -m 1 "^\[assembly: ?AssemblyVersion" ${shared_version_file} \
            | sed -E 's/\[assembly: ?AssemblyVersion\("([0-9\.]+)"\)\]/\1/'
    )"
    echo "old assembly version: ${old_version}"
    # Replace the versions in AssemblyVersion, AssemblyFileVersion, and AssemblyInformationalVersion attributes
    sed -i -E "s/(\[assembly: ?Assembly(File|Informational)?Version\(\")${old_version}(\"\)\])/\1${new_version_sed}\3/g" "${shared_version_file}"
fi

# update nuget package version
for subproject in ${jellyfin_subprojects[@]}; do
    if [[ -f ${subproject} ]]; then
        echo "${subproject}"
        # Parse the version from the *.csproj file
        old_version="$(
            grep -m 1 "<VersionPrefix>" "${subproject}" \
                | awk '{$1=$1};1' \
                | sed -E 's/<VersionPrefix>([0-9\.]+[-a-z0-9]*)<\/VersionPrefix>/\1/'
        )"
        echo "old nuget version: ${old_version}"

        # Set the nuget version to the specified new_version
        sed -i "s|<VersionPrefix>${old_version}</VersionPrefix>|<VersionPrefix>${new_version_sed}</VersionPrefix>|g" "${subproject}"
    fi
done

# Set the version in the GitHub issue template file
if [[ -f ${issue_template_file} ]]; then
    # Extract the first version from the options list in the issue template
    old_issue_version=$(grep -m 1 "        - [0-9]" "${issue_template_file}" | awk '{print $2}')
    if [[ -n ${old_issue_version} ]]; then
        sed -i "s|        - ${old_issue_version}|        - ${new_version_sed}|g" "${issue_template_file}"
    fi
fi

# Set the version in the HAOS config file
if [[ -f ${haos_config_file} ]]; then
    old_haos_version=$(grep "^version: " "${haos_config_file}" | cut -d '"' -f 2)
    echo old HAOS version: $old_haos_version
    sed -i "s|version: \"${old_haos_version}\"|version: \"${new_version_sed}\"|g" "${haos_config_file}"
fi

# Update HAOS changelog
if [[ -f ${haos_changelog_file} ]]; then
    if ! grep -q "## ${new_version_sed}" "${haos_changelog_file}"; then
        sed -i "s/# Changelog/# Changelog\n\n## ${new_version_sed}\n- Automated version bump to ${new_version_sed}./" "${haos_changelog_file}"
    fi
fi

# Stage the changed files for commit
git add .
git status -v
