#!/bin/bash
#uname -a
#cat /proc/sys/fs/binfmt_misc/qemu-arm
#apt-get update
#apt-get install -y curl qemu-user-static binfmt-support
#cat /proc/sys/fs/binfmt_misc/qemu-arm
# local copy of qemu binary 
#cp -p $(which qemu-arm-static) .
# downloads a local copy of qemu on docker-hub build machines
curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-aarch64/qemu-aarch64-static .
