//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Jellyfin.Data
{
   public partial class Episode: global::Jellyfin.Data.LibraryItem
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Episode(): base()
      {
         // NOTE: This class has one-to-one associations with LibraryRoot, LibraryItem and CollectionItem.
         // One-to-one associations are not validated in constructors since this causes a scenario where each one must be constructed before the other.

         Releases = new System.Collections.Generic.HashSet<global::Jellyfin.Data.Release>();
         EpisodeMetadata = new System.Collections.Generic.HashSet<global::Jellyfin.Data.EpisodeMetadata>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Episode CreateEpisodeUnsafe()
      {
         return new Episode();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="urlid">This is whats gets displayed in the Urls and APi requests. This could also be a string.</param>
      /// <param name="_season0"></param>
      public Episode(Guid urlid, DateTime dateadded, global::Jellyfin.Data.Season _season0)
      {
         // NOTE: This class has one-to-one associations with LibraryRoot, LibraryItem and CollectionItem.
         // One-to-one associations are not validated in constructors since this causes a scenario where each one must be constructed before the other.

         this.UrlId = urlid;

         if (_season0 == null) throw new ArgumentNullException(nameof(_season0));
         _season0.Episodes.Add(this);

         this.Releases = new System.Collections.Generic.HashSet<global::Jellyfin.Data.Release>();
         this.EpisodeMetadata = new System.Collections.Generic.HashSet<global::Jellyfin.Data.EpisodeMetadata>();

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="urlid">This is whats gets displayed in the Urls and APi requests. This could also be a string.</param>
      /// <param name="_season0"></param>
      public static Episode Create(Guid urlid, DateTime dateadded, global::Jellyfin.Data.Season _season0)
      {
         return new Episode(urlid, dateadded, _season0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Backing field for EpisodeNumber
      /// </summary>
      protected int? _EpisodeNumber;
      /// <summary>
      /// When provided in a partial class, allows value of EpisodeNumber to be changed before setting.
      /// </summary>
      partial void SetEpisodeNumber(int? oldValue, ref int? newValue);
      /// <summary>
      /// When provided in a partial class, allows value of EpisodeNumber to be changed before returning.
      /// </summary>
      partial void GetEpisodeNumber(ref int? result);

      public int? EpisodeNumber
      {
         get
         {
            int? value = _EpisodeNumber;
            GetEpisodeNumber(ref value);
            return (_EpisodeNumber = value);
         }
         set
         {
            int? oldValue = _EpisodeNumber;
            SetEpisodeNumber(oldValue, ref value);
            if (oldValue != value)
            {
               _EpisodeNumber = value;
            }
         }
      }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::Jellyfin.Data.Release> Releases { get; protected set; }

      public virtual ICollection<global::Jellyfin.Data.EpisodeMetadata> EpisodeMetadata { get; protected set; }

   }
}

