//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Jellyfin.Data
{
   public partial class MediaFile
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected MediaFile()
      {
         MediaFileStreams = new System.Collections.Generic.HashSet<global::Jellyfin.Data.MediaFileStream>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static MediaFile CreateMediaFileUnsafe()
      {
         return new MediaFile();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="path">Relative to the LibraryRoot</param>
      /// <param name="kind"></param>
      /// <param name="_release0"></param>
      public MediaFile(string path, global::Jellyfin.Data.MediaFileKind kind, global::Jellyfin.Data.Release _release0)
      {
         if (string.IsNullOrEmpty(path)) throw new ArgumentNullException(nameof(path));
         this.Path = path;

         this.Kind = kind;

         if (_release0 == null) throw new ArgumentNullException(nameof(_release0));
         _release0.MediaFiles.Add(this);

         this.MediaFileStreams = new System.Collections.Generic.HashSet<global::Jellyfin.Data.MediaFileStream>();

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="path">Relative to the LibraryRoot</param>
      /// <param name="kind"></param>
      /// <param name="_release0"></param>
      public static MediaFile Create(string path, global::Jellyfin.Data.MediaFileKind kind, global::Jellyfin.Data.Release _release0)
      {
         return new MediaFile(path, kind, _release0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Backing field for Id
      /// </summary>
      internal int _Id;
      /// <summary>
      /// When provided in a partial class, allows value of Id to be changed before setting.
      /// </summary>
      partial void SetId(int oldValue, ref int newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Id to be changed before returning.
      /// </summary>
      partial void GetId(ref int result);

      /// <summary>
      /// Identity, Indexed, Required
      /// </summary>
      [Key]
      [Required]
      public int Id
      {
         get
         {
            int value = _Id;
            GetId(ref value);
            return (_Id = value);
         }
         protected set
         {
            int oldValue = _Id;
            SetId(oldValue, ref value);
            if (oldValue != value)
            {
               _Id = value;
            }
         }
      }

      /// <summary>
      /// Backing field for Path
      /// </summary>
      protected string _Path;
      /// <summary>
      /// When provided in a partial class, allows value of Path to be changed before setting.
      /// </summary>
      partial void SetPath(string oldValue, ref string newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Path to be changed before returning.
      /// </summary>
      partial void GetPath(ref string result);

      /// <summary>
      /// Required, Max length = 65535
      /// Relative to the LibraryRoot
      /// </summary>
      [Required]
      [MaxLength(65535)]
      [StringLength(65535)]
      public string Path
      {
         get
         {
            string value = _Path;
            GetPath(ref value);
            return (_Path = value);
         }
         set
         {
            string oldValue = _Path;
            SetPath(oldValue, ref value);
            if (oldValue != value)
            {
               _Path = value;
            }
         }
      }

      /// <summary>
      /// Backing field for Kind
      /// </summary>
      protected global::Jellyfin.Data.MediaFileKind _Kind;
      /// <summary>
      /// When provided in a partial class, allows value of Kind to be changed before setting.
      /// </summary>
      partial void SetKind(global::Jellyfin.Data.MediaFileKind oldValue, ref global::Jellyfin.Data.MediaFileKind newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Kind to be changed before returning.
      /// </summary>
      partial void GetKind(ref global::Jellyfin.Data.MediaFileKind result);

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public global::Jellyfin.Data.MediaFileKind Kind
      {
         get
         {
            global::Jellyfin.Data.MediaFileKind value = _Kind;
            GetKind(ref value);
            return (_Kind = value);
         }
         set
         {
            global::Jellyfin.Data.MediaFileKind oldValue = _Kind;
            SetKind(oldValue, ref value);
            if (oldValue != value)
            {
               _Kind = value;
            }
         }
      }

      /// <summary>
      /// Required
      /// </summary>
      [ConcurrencyCheck]
      [Required]
      public byte[] Timestamp { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::Jellyfin.Data.MediaFileStream> MediaFileStreams { get; protected set; }

   }
}

