//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Jellyfin.Data
{
   public partial class MusicAlbum: global::Jellyfin.Data.LibraryItem
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected MusicAlbum(): base()
      {
         MusicAlbumMetadata = new System.Collections.Generic.HashSet<global::Jellyfin.Data.MusicAlbumMetadata>();
         Tracks = new System.Collections.Generic.HashSet<global::Jellyfin.Data.Track>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static MusicAlbum CreateMusicAlbumUnsafe()
      {
         return new MusicAlbum();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="urlid">This is whats gets displayed in the Urls and APi requests. This could also be a string.</param>
      /// <param name="lastmodified"></param>
      public MusicAlbum(Guid urlid, DateTime dateadded, DateTime lastmodified)
      {
         this.UrlId = urlid;

         this.LastModified = lastmodified;

         this.MusicAlbumMetadata = new System.Collections.Generic.HashSet<global::Jellyfin.Data.MusicAlbumMetadata>();
         this.Tracks = new System.Collections.Generic.HashSet<global::Jellyfin.Data.Track>();

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="urlid">This is whats gets displayed in the Urls and APi requests. This could also be a string.</param>
      /// <param name="lastmodified"></param>
      public static MusicAlbum Create(Guid urlid, DateTime dateadded, DateTime lastmodified)
      {
         return new MusicAlbum(urlid, dateadded, lastmodified);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Concurrency token
      /// </summary>
      [Timestamp]
      public Byte[] Timestamp { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::Jellyfin.Data.MusicAlbumMetadata> MusicAlbumMetadata { get; protected set; }

      public virtual ICollection<global::Jellyfin.Data.Track> Tracks { get; protected set; }

   }
}

