//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Jellyfin.Data
{
   public enum PreferenceKind : Int32
   {
      MaxParentalRating,
      BlockedTags,
      RemoteClientBitrateLimit,
      EnabledDevices,
      EnabledChannels,
      EnabledFolders,
      EnableContentDeletionFromFolders
   }
}
