name: Add-on Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Home Assistant Add-on Linter
        uses: frenck/action-addon-linter@v2.18.0
        with:
          path: "./haos-jellyfin"
