name: Add-on Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.repository, 'haos-jellyfin') }}
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Add-on
        uses: docker/build-push-action@v5
        with:
          context: ./haos-jellyfin
          platforms: ${{ matrix.platform }}
          push: false
