name: Format
on:
  push:
    branches:
      - master
  pull_request:

env:
  SDK_VERSION: "10.0.103"

jobs:
  format-check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.repository, 'haos-jellyfin') }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.SDK_VERSION }}

      - name: Run DotNet Format
        run: dotnet format --verify-no-changes --verbosity minimal
