name: Tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  SDK_VERSION: "10.0.103"

jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
      fail-fast: false

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.SDK_VERSION }}

      - name: Run DotNet CLI Tests
        run: >
          dotnet test Jellyfin.sln
          --configuration Release
          --collect:"XPlat Code Coverage"
          --settings tests/coverletArgs.runsettings
          --verbosity minimal

      - name: Merge code coverage results
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "merged/"
          reporttypes: "Cobertura"
