name: OpenAPI Generate

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repository:
        required: true
        type: string
      artifact:
        required: true
        type: string

permissions:
  contents: read

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    if: ${{ contains(github.repository, 'haos-jellyfin') }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}

    - name: Configure .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.103'

    - name: Generate OpenAPI Spec
      run: dotnet test tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj -c Release --filter Jellyfin.Server.Integration.Tests.OpenApiSpecTests

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: tests/Jellyfin.Server.Integration.Tests/bin/Release/net10.0/openapi.json
        retention-days: 14
        if-no-files-found: error
