name: Merge Conflict Labeler

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [synchronize]

permissions: {}
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.repository == 'jellyfin/jellyfin' }}
    steps:
      - name: Apply label
        uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1 # v3.1.0
        with:
          dirtyLabel: 'merge conflict'
          commentOnDirty: 'This pull request has merge conflicts. Please resolve the conflicts so the PR can be successfully reviewed and merged.'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
